[package]
name = "mapmysite"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
quick-xml = { version = "0.38.3", features = ["serde", "serialize"] }
serde = { version = "1.0.219", features = ["derive"] }
